# deployments/k8s/servicemonitor.yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
    name: payment-service
    namespace: payment-service
    labels:
        app: payment-service
spec:
    selector:
        matchLabels:
            app: payment-service
    endpoints:
        - port: http
          path: /metrics
          interval: 30s

---

