# monitoring/rules/payment-service.yml
groups:
    - name: payment-service
      rules:
          - alert: PaymentServiceDown
            expr: up{job="payment-service"} == 0
            for: 1m
            labels:
                severity: critical
            annotations:
                summary: 'Payment Service is down'
                description: 'Payment Service has been down for more than 1 minute'

          - alert: HighErrorRate
            expr: rate(http_requests_total{status=~"5.."}[5m]) > 0.1
            for: 5m
            labels:
                severity: warning
            annotations:
                summary: 'High error rate detected'
                description: 'Error rate is above 10% for 5 minutes'

          - alert: HighResponseTime
            expr: histogram_quantile(0.95, rate(http_request_duration_seconds_bucket[5m])) > 1
            for: 5m
            labels:
                severity: warning
            annotations:
                summary: 'High response time'
                description: '95th percentile response time is above 1 second'

          - alert: DatabaseConnectionsHigh
            expr: pg_stat_activity_count > 80
            for: 5m
            labels:
                severity: warning
            annotations:
                summary: 'High database connections'
                description: 'Database connections are above 80'

          - alert: RedisMemoryHigh
            expr: redis_memory_used_bytes / redis_memory_max_bytes > 0.9
            for: 5m
            labels:
                severity: warning
            annotations:
                summary: 'Redis memory usage high'
                description: 'Redis memory usage is above 90%'

          - alert: PaymentProcessingFailed
            expr: increase(payments_failed_total[5m]) > 10
            for: 1m
            labels:
                severity: critical
            annotations:
                summary: 'High payment failure rate'
                description: 'More than 10 payment failures in the last 5 minutes'
