# kubernetes/secret.yaml
apiVersion: v1
kind: Secret
metadata:
    name: auth-service-secrets
    namespace: auth-service
type: Opaque
stringData:
    DB_PASSWORD: "your-secure-db-password"
    JWT_ACCESS_SECRET: "your-super-secret-jwt-access-key-change-in-production"
    JWT_REFRESH_SECRET: "your-super-secret-jwt-refresh-key-change-in-production"
    REDIS_PASSWORD: "your-redis-password"
    SMTP_PASSWORD: "your-smtp-password"

---

